services:
  modu-api:
    container_name: modu-api
    restart: always
    image: node:20
    ports:
      - '3009:3009'
    volumes:
      - ./:/usr/src/modu
    working_dir: /usr/src/modu

    networks:
      - monorepo-network
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  modu-batch:
    container_name: modu-batch
    restart: unless-stopped
    image: node:20
    ports:
      - '3005:3005'
    volumes:
      - ./:/usr/src/modu
    working_dir: /usr/src/modu

    networks:
      - monorepo-network
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# docker compose up -d
# docker compose stop
# docker compose start
# docker compose restart
# docker compose stop && # docker compose rm -f

